### PR TITLE
Added version and better readme

### PR DESCRIPTION
**Pull request by theisjendal**
image

### CODE REVIEW

**Comment by bruunand** [comment]
Hi @tj45794,

Thanks for your pull request.

Have you confirmed that the versions are working as expected with a clean virtual environment?

**Comment by bruunand** [comment]
@theisjendal please respond

**Comment by Minibrams** [comment]
@theisjendal 😢

**Comment by bruunand** [comment]
@theisjendal this PR will be closed soon ok?

**Pull request merged**
